[1, 3, 5]: "basic"
[1, 3, 5, 7]: "basic"
[1, 3, 7]: "basic"
[1, 3]: "basic"
[3, 5]: "basic"
[1, 3, 6]: "first"
[1, 3, 5, 6]: "first"
[1, 5, 6]: "first"
[1, 6]: "first"
[1, 4, 6]: "second"
[1, 3, 4, 6]: "second"
# fa - ti is 5 degree defined
[1, 2, 5, 6]: "third"
